# Numpy 

Numpy é uma biblioteca de álgebra linear para Python, a razão pela qual é tão importante para a Data Science com Python é que quase todas as bibliotecas dependem do Numpy como um dos seus principais blocos de construção.

Numpy também é incrivelmente rápido, pois tem ligações para bibliotecas C. Para obter mais informações sobre porque você deseja usar Arrays em vez de listas, confira esta publicação do [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

* Permite a criação de arrays homogêneos
* Pode ser criado a partir de uma lista ou tupla do python ou pode ser criado usando seus próprios métodos 

In [1]:
#Importar biblioteca usando alias
import numpy as np

## Numpy Arrays

Numpy arrays essencialmente vêm de duas formas: vetores e matrizes.

### Criando Numpy Arrays

Podemos criar uma matriz convertendo diretamente uma lista ou lista de listas:

In [2]:
minha_lista = [1,2,3]
minha_lista

[1, 2, 3]

In [3]:
vetor = np.array(minha_lista)

In [4]:
type(vetor)

numpy.ndarray

In [8]:
print(vetor)

[1 2 3]


In [98]:
minha_matriz = [[1,2,3],[4,5,6],[7,8,9]]
minha_matriz

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [103]:
matriz = np.array(minha_matriz)

In [104]:
print(matriz)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Tipos dos elementos

Os elementos do array numpy são do mesmo tipo (estrutura homogênea)

In [5]:
mlista = [12.5, 'laura', 35]
print(mlista)

[12.5, 'laura', 35]


In [7]:
type(mlista[1])

str

In [8]:
marray = np.array(mlista)

In [9]:
print(marray)

['12.5' 'laura' '35']


In [11]:
type(marray[0])

numpy.str_

In [124]:
type(marray)

numpy.ndarray

## Métodos incorporados (Built-in Methods)

Há muitas maneiras embutidas de gerar numpy arrays

### arange

Retorna valores uniformemente espaçados dentro de um determinado intervalo.

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros e ones

Gerar matrizes de zeros ou de uns

In [11]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [12]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [13]:
np.ones(3)

array([ 1.,  1.,  1.])

In [14]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

### linspace
Retorna números uniformemente espaçados ao longo de um intervalo especificado.

In [15]:
np.linspace(0,10,3)

array([  0.,   5.,  10.])

In [16]:
np.linspace(0,10,50)

array([  0.        ,   0.20408163,   0.40816327,   0.6122449 ,
         0.81632653,   1.02040816,   1.2244898 ,   1.42857143,
         1.63265306,   1.83673469,   2.04081633,   2.24489796,
         2.44897959,   2.65306122,   2.85714286,   3.06122449,
         3.26530612,   3.46938776,   3.67346939,   3.87755102,
         4.08163265,   4.28571429,   4.48979592,   4.69387755,
         4.89795918,   5.10204082,   5.30612245,   5.51020408,
         5.71428571,   5.91836735,   6.12244898,   6.32653061,
         6.53061224,   6.73469388,   6.93877551,   7.14285714,
         7.34693878,   7.55102041,   7.75510204,   7.95918367,
         8.16326531,   8.36734694,   8.57142857,   8.7755102 ,
         8.97959184,   9.18367347,   9.3877551 ,   9.59183673,
         9.79591837,  10.        ])

## eye

Cria uma matriz identidade

In [17]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

### Random 

Numpy também tem muitas maneiras de criar arrays de números aleatórios:

### rand
Cria uma matriz da forma dada e preencha com amostras aleatórias de uma distribuição uniforme sobre ``[0, 1)``.

In [127]:
np.random.rand(2)

array([0.92244399, 0.57038821])

In [128]:
np.random.rand(2)*10

array([5.66522554, 8.30381741])

In [21]:
np.random.rand(5,5)

array([[ 0.17673782,  0.89778905,  0.63435534,  0.71063947,  0.77599807],
       [ 0.43508517,  0.91318032,  0.26845102,  0.47684911,  0.99352832],
       [ 0.46549283,  0.61358868,  0.83033769,  0.96269353,  0.40539354],
       [ 0.42690345,  0.62643046,  0.63229206,  0.70472064,  0.56361411],
       [ 0.64975573,  0.99581894,  0.22271032,  0.98653378,  0.81032733]])

### randint
Retorna inteiros aleatórios de "low" (inclusive) para "high" (exclusivo).

In [137]:
np.random.randint(5) #entre 0 e 4

3

In [139]:
np.random.randint(1,5,10) #entre 1 e 4, 10 elementos

array([1, 1, 3, 2, 3, 3, 4, 4, 4, 2])

In [144]:
np.random.randint(1,5, size=(2, 4)) #entre 1 e 4, matriz 2X4

array([[4, 4, 3, 2],
       [4, 1, 1, 4]])

### Reshape
Retorna uma matriz contendo os mesmos dados com uma nova forma.

In [3]:
arr = np.arange(12)

In [4]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [9]:
arr2 = arr.reshape(4,3)

In [6]:
print(arr2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


### max,min,argmax,argmin

Estes são métodos úteis para encontrar valores máximos ou mínimos, ou para encontrar seus locais de índice usando argmin ou argmax

In [16]:
ranarr = np.random.randint(0,50,10)

In [19]:
print(ranarr)

[45 30 19 45 17 24  2 41 27 27]


In [21]:
ranarr.max()

45

In [22]:
ranarr.argmax()

0

In [23]:
ranarr.min()

2

In [24]:
ranarr.argmin()

6

## Shape

Shape é um atributo que os arrays têm que retorna a dimensão do array

In [10]:
arr2.shape

(4, 3)

## Indexação
A maneira mais simples de escolher um ou alguns elementos de uma matriz é muito semelhante às listas de python:

In [4]:
# Obtendo um valor através de um índice
arr[8]

8

In [5]:
# Obtendo valores em um intervalo
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

### Indexação de matrizes

No caso de matrizes, pode-se usar duplo colchetes ou um colchete separando as dimensões por vírgula

In [114]:
mat = np.random.rand(4,3)

In [67]:
mat

array([[0.24870109, 0.55104188, 0.13583963],
       [0.07351891, 0.41261426, 0.73055113],
       [0.26196355, 0.01275437, 0.71938719],
       [0.34774946, 0.03430436, 0.10906137]])

In [68]:
mat[0,0]

0.24870109373075144

In [69]:
mat[0:2, 0:2]

array([[0.24870109, 0.55104188],
       [0.07351891, 0.41261426]])

In [70]:
mat.shape

(4, 3)

## Transmissão

Pode-se aplicar um valor ou operação a todo o array ou parte dele

In [46]:
# Configurando um valor com intervalo de índice (Transmissão)
arr[0:5]=100

#Show
print(arr)

[100 100 100 100 100   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24]


In [47]:
# Notas importantes sobre fatias
slice_de_arr = arr[0:6]

# Mostra a fatia
print(slice_de_arr)

[100 100 100 100 100   5]


In [48]:
# Modifica a fatia
slice_de_arr[:]=99

#Show Slice again
slice_de_arr

array([99, 99, 99, 99, 99, 99])

Agora note que as mudanças também ocorrem em nossa matriz original!

In [49]:
print(arr)

[99 99 99 99 99 99  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


Os dados não são copiados, é uma visão da matriz original! Isso evita problemas de memória!

In [50]:
# Para obter uma cópia, precisa ser explícito
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

## Seleção condicional

Vamos examinar brevemente como usar colchetes para seleção com base em operadores de comparação.

In [51]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [10]:
arrMaiorQuatro = arr[arr > 4]

In [11]:
print(arrMaiorQuatro)

[ 5  6  7  8  9 10]


A seleção condicional é semelhante ao Filter, já que ele aplica a condição ao array, retornando apenas os valores que retornam True